---
apiVersion: v1
kind: Template
metadata:
  name: container-security-operator
objects:
- apiVersion: operators.coreos.com/v1
  kind: OperatorGroup
  metadata:
    name: container-security-operator
    namespace: ${TARGET_NAMESPACE}
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: container-security-operator
    namespace: ${TARGET_NAMESPACE}
  spec:
    channel: quay-v3.3
    name: container-security-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
parameters:
- name: TARGET_NAMESPACE
  value: container-security-operator
